name = "AdventOfCode2021"
authors = ["Brynjar Smári Bjarnason"]

[deps]
AOC2021 = "8074e4e6-93b1-4cb4-9423-4aa0b28e125c"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"

[compat]
DrWatson = "2.7.5"
julia = "1.7.0"
